name: Docker 构建与测试

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: 设置 Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: 构建 Docker 镜像
      uses: docker/build-push-action@v4
      with:
        context: .
        push: false
        load: true
        tags: openai-realtime-console:test
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: 测试 Docker 镜像
      run: |
        docker run --name test-container -d --env NODE_ENV=test openai-realtime-console:test
        sleep 5
        if [ "$(docker inspect -f {{.State.Running}} test-container)" != "true" ]; then
          echo "容器未能成功运行"
          docker logs test-container
          exit 1
        fi
        echo "容器成功运行"
        docker logs test-container
        docker stop test-container
    
    - name: 清理
      if: always()
      run: docker rm -f test-container || true 